# Generated by Django 4.0 on 2022-06-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='caution.jpeg', upload_to='project_pics'),
        ),
    ]
