# Generated by Django 4.0 on 2022-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='period',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '6'), ('7', '7')], default='', max_length=1),
        ),
    ]
