# Generated by Django 4.0 on 2022-06-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='gallery_pics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='project_pics'),
        ),
    ]
