# Generated by Django 4.0 on 2022-06-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_galleryphoto_photo_alter_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='description',
        ),
    ]
