# Generated by Django 4.0 on 2022-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='period',
            field=models.IntegerField(),
        ),
    ]
