# Generated by Django 4.0 on 2022-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_photo_galleryphoto_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='gallery_photo',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='gallery_pics'),
        ),
    ]
