# Generated by Django 4.0 on 2022-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_galleryphoto_gallery_photo_galleryphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='project_pics'),
        ),
    ]
