# Generated by Django 4.0 on 2022-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='project_pics'),
        ),
    ]
