# Generated by Django 4.0 on 2022-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='period',
        ),
    ]
