# Generated by Django 4.0 on 2022-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
