# Generated by Django 4.0 on 2022-06-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_galleryphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='description',
        ),
    ]
