# Generated by Django 4.0 on 2022-06-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_galleryphoto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
