# Generated by Django 4.0 on 2022-05-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='period',
        ),
    ]
