# Generated by Django 4.0 on 2022-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_galleryphoto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='gallery_pics'),
        ),
    ]
