# Generated by Django 4.0 on 2022-06-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_project_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='school_year',
        ),
    ]
