# Generated by Django 4.0 on 2022-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Home', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Simpson', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
