# Generated by Django 4.0 on 2022-05-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_first_name_profile_last_name_profile_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
