# Generated by Django 4.0 on 2022-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_blurb',
            field=models.CharField(default='Check out my project!', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_description',
            field=models.TextField(default="I don't have a project description yet, but trust me it will be awesome!"),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_title',
            field=models.CharField(default='My EXAP project', max_length=50),
        ),
    ]
