# Generated by Django 4.0 on 2022-06-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_galleryphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='description',
        ),
    ]
