# Generated by Django 4.0 on 2022-05-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_blurb',
            field=models.CharField(default='Check out my project', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_description',
            field=models.TextField(default="I haven't written my project description yet, but trust me it will be awesome!"),
        ),
    ]
