# Generated by Django 4.0 on 2022-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_profile_comment_project_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
