# Generated by Django 4.0 on 2022-05-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='profile',
        ),
    ]
