# Generated by Django 4.0 on 2022-05-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0025_alter_comment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=1)),
                ('title', models.CharField(default='My EXAP project', max_length=50)),
                ('blurb', models.CharField(default='Check out my project', max_length=100)),
                ('description', models.TextField(default="I haven't written my project description yet, but trust me it will be awesome!")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_blurb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
