# Generated by Django 4.0 on 2022-05-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_project_remove_profile_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='student',
        ),
    ]
