# Generated by Django 4.0 on 2022-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_project_liked_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (7, 7)], default=1),
        ),
    ]
