# Generated by Django 4.0 on 2022-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_project_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=E-xhxS581Uc', max_length=1000),
        ),
    ]
