# Generated by Django 4.0 on 2022-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_project_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
