# Generated by Django 4.0 on 2022-06-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.project'),
        ),
    ]
