# Generated by Django 4.0 on 2022-06-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_soup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soup',
        ),
    ]
