# Generated by Django 4.0 on 2022-06-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_projectvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectvideo',
            old_name='url',
            new_name='URL',
        ),
    ]
