# Generated by Django 4.0 on 2022-06-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_projectvideo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
    ]
