# Generated by Django 4.0 on 2022-06-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_url_projectvideo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectVideo',
        ),
    ]
