# Generated by Django 4.0 on 2022-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_projectvideo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
