# Generated by Django 4.0 on 2022-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_video_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='url',
        ),
    ]
