# Generated by Django 4.0 on 2022-06-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_video_project'),
        ('users', '0035_rename_video_video_url'),
    ]

    operations = [
    ]
