# Generated by Django 4.0 on 2022-06-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_project_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='ProjectVideo',
        ),
    ]
