# Generated by Django 4.0 on 2022-06-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='video_url',
        ),
    ]
