# Generated by Django 4.0 on 2022-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_delete_projectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
