# Generated by Django 4.0 on 2022-06-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rename_url_project_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='video_url',
            new_name='video_URL',
        ),
    ]
