# Generated by Django 4.0 on 2022-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.CharField(default='Check out my project!', max_length=100),
        ),
    ]
